switch to single serializer, added validation
Price-Aggregator/AroundRussia_backend pull request #43
Opened 2023-07-16 00:38 UTC by Algor45

Перестроил на работу через единый сериализатор и эндпоинт, добавил валидацию.
Поправил вывод списка активностей.
Создал mixin для активностей.

2023-07-16 07:17 UTC, rosh-penin commented on backend/api/serializers.py
> +    activity = ActivityListSerializer(many=True, source='travel')
В списке путешествий у нас ведь не должно быть активностей. Активности мы отдаем когда пользователь открывает конкретное путешествие

2023-07-16 07:18 UTC, rosh-penin commented on backend/api/serializers.py
> +                  'travel')
travel это ведь несуществующее поле?

2023-07-16 07:22 UTC, rosh-penin commented on backend/api/serializers.py
> +            if 'origin' not in data or 'destination' not in data:
Если origin или destination будут присутствовать в data, но будут пусты - ошибки не выкинет, но логика нарушится и в модель запишется "неправильное" значение?

2023-07-16 07:24 UTC, rosh-penin commented on backend/api/serializers.py
> +            if 'origin' not in data or 'destination' not in data:
Если правильно помню то data это словарь, а значит можно получить origin = data.get('origin')  и после проверить как if origin:. Данным образом мы проверяем наличие этого ключа в словаре и что его значение не преобразуется в булевое False (пустая строка, например)

2023-07-16 07:26 UTC, rosh-penin commented on backend/api/views.py
> +        if self.request.method in SAFE_METHODS:
Тут получается что get_object() нам вернет TravelListSerializer, а должен вернуть TravelSerializer. Предыдущая проверка на list выглядела более логично

2023-07-16 07:28 UTC, rosh-penin commented on backend/api/views.py
> +class CreateDestroyRetrieveUpdateViewSet(
Выглядит как лишний кусок кода. Мы ведь используем его только в одном месте, а значит можем напрямую наследовать все указанные в наследовании миксины и GenericViewSet в самом ActivityViewSet

2023-07-16 07:31 UTC, rosh-penin requested changes
Либо я плохо понял логику, которую ты пытаешься тут реализовать, либо нужно переделать согласно комментариям. И опять сильная переделка логики путешествий - чужого блока кода.

2023-07-16 07:44 UTC, IgorKrupko-94 commented on backend/api/serializers.py
> +                  'travel')
Да, раньше было travel, потом стало activity. 
В общем список полей выглядит так: name, start_date, end_date, image, traveler, activity

2023-07-17 09:26 UTC, rosh-penin commented on backend/api/serializers.py
> +        fields = ('name', 'start_date', 'end_date', 'image', 'traveler')
Сверху указано кастомное поле activity, но оно не вписано в fields

2023-07-17 09:30 UTC, rosh-penin commented on backend/api/serializers.py
> +        fields = TravelSerializer.Meta.fields + ('activity',)
А где остальное? При получении одного путешествия (а ведь именно это мы пытаемся сделать?) нужно отдать все необходимые для путешествия данные

2023-07-17 09:31 UTC, rosh-penin requested changes
Если мои комментарии актуальны - нужно исправить

2023-07-17 17:06 UTC, rosh-penin commented on backend/api/serializers.py
> +        fields = TravelSerializer.Meta.fields + ('activity',)
Моя ошибка, не увидел Meta.fields

2023-07-17 17:13 UTC, merged